import type { RelativeType } from './Relative.ts';

/**
 * This file was automatically generated by jyst package.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run jyst to regenerate this file.
 */

/**
 * Object in subdir referencing another file in same subdir
 */
export interface SubType {
  relative: RelativeType;
}
