import type { RelativeType } from './Relative.ts';
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Object in subdir referencing another file in same subdir
 */
export interface SubType {
  relative: RelativeType;
}
