
/**
 * This file was automatically generated by jyst package.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run jyst to regenerate this file.
 */

/**
 * Schema in a subdirectory with a Map referencing the same type (regression test for nested $ref relativization)
 */
export interface Field {
  name: string;
  children: {
    [k: string]: Field;
  };
}
