import type { CircularB } from './CircularB.ts';
/**
 * This file was automatically generated by jyst package.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run jyst to regenerate this file.
 */

/**
 * Type A referencing Type B
 */
export interface CircularA {
  b: CircularB;
}
