import type { CircularA } from './CircularA.ts';
/**
 * This file was automatically generated by jyst package.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run jyst to regenerate this file.
 */

/**
 * Type B referencing Type A
 */
export interface CircularB {
  a: CircularA;
}
