import type { CircularB } from './CircularB.ts';
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Type A referencing Type B
 */
export interface CircularA {
  b: CircularB;
}
