/**
 * This file was automatically generated by jyst package.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run jyst to regenerate this file.
 */

/**
 * Complex types including nesting and generics
 */
export interface Complex {
  listOfLists: string[][];
  mapOfLists: {
    [k: string]: number[];
  };
  anyObject: string | number | boolean | null;
  wildcardList: (string | number | boolean | null)[];
}
