/**
 * This file was automatically generated by jyst package.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run jyst to regenerate this file.
 */

/**
 * JSON representation of an entity type
 */
export interface EntityType {
  entity_type: 'user' | 'order' | 'session' | 'content';
}
