/**
 * This file was automatically generated by jyst package.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run jyst to regenerate this file.
 */

/**
 * Object where a property is an enum with its own javaType (like DecisionJsonType)
 */
export interface EnumInProperty {
  status: 'active' | 'disabled' | 'deleted';
  type: 'red' | 'yellow' | 'green';
  name: string;
}
