
/**
 * This file was automatically generated by jyst package.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run jyst to regenerate this file.
 */

/**
 * Source schema that owns an enum property referenced by other schemas via fragment $ref
 */
export interface EnumSource {
  status: 'active' | 'inactive' | 'pending';
  name: string;
}
