import type { EnumSource } from './EnumSource.ts';

/**
 * This file was automatically generated by jyst package.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run jyst to regenerate this file.
 */

/**
 * Schema that references a property fragment from another file — $ref file.yaml#properties/field
 */
export interface FragmentRef {
  status: EnumSource['status'];
  count?: number;
}
