import type { EnumSource } from './EnumSource.ts';
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema that references a property fragment from another file — $ref file.yaml#properties/field
 */
export interface FragmentRef {
  status: EnumSource['status'];
  count?: number;
}
