/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A generic wrapper type — file-level generic type parameter T
 */
export interface GenericWrapper<T = unknown> {
  data: T[];
  count: number;
  has_more: boolean;
}
