
/**
 * This file was automatically generated by jyst package.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run jyst to regenerate this file.
 */

/**
 * A generic wrapper type — file-level generic type parameter T
 */
export interface GenericWrapper<T = unknown> {
  data: T[];
  count: number;
  has_more: boolean;
}
