/**
 * This file was automatically generated by jyst package.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run jyst to regenerate this file.
 */

export interface GeocodingFeature {
  address: string;
  place: string;
  region: string;
  country_code: string;
  postcode: string;
  coordinates: {
    longitude: number;
    latitude: number;
  };
}
