/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Object with array items that carry their own inline javaType and sub-properties
 */
export interface InlineItems {
  signals: {
    name: string;
    impact: number;
    active?: boolean;
  }[];
}
