/**
 * This file was automatically generated by jyst package.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run jyst to regenerate this file.
 */

/**
 * Object with array items that carry their own inline javaType and sub-properties
 */
export interface InlineItems {
  signals: {
    name: string;
    impact: number;
    active?: boolean;
  }[];
}
