import type { MyEnum } from './Enums.ts';
import type { NestedObject } from './Nested.ts';
import type { SubType } from './subdir/Sub.ts';
import type { RelativeType } from './subdir/Relative.ts';

/**
 * This file was automatically generated by jyst package.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run jyst to regenerate this file.
 */

/**
 * The main entry point testing various references
 */
export interface MainObject {
  simpleField: string;
  enumField: MyEnum;
  nestedRef: NestedObject;
  subDirRef: SubType;
  mapField: {
    [k: string]: RelativeType;
  };
  listField: RelativeType[];
  innerClass: {
    innerField: number;
  };
}
