import type { NestedObject } from './Nested.ts';
/**
 * This file was automatically generated by jyst package.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run jyst to regenerate this file.
 */

/**
 * Object with various map structures including Map<String, Map<String, primitive>>
 */
export interface NestedMapType {
  scores: {
    [k: string]: number;
  };
  counters: {
    [k: string]: {
      [k: string]: number;
    };
  };
  byRef: {
    [k: string]: NestedObject;
  };
}
