/**
 * This file was automatically generated by jyst package.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run jyst to regenerate this file.
 */

/**
 * An object with a nested Java type definition
 */
export interface NestedObject {
  id: string;
  child: {
    name: string;
  };
}
