/**
 * This file was automatically generated by jyst package.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run jyst to regenerate this file.
 */

export interface ReviewQueueColumn {
  id: string;
  name: string;
  entityType: string;
  sortable: boolean;
  default: boolean;
  static: boolean;
  description: string;
}
