/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ReviewQueueColumn {
  id: string;
  name: string;
  entityType: string;
  sortable: boolean;
  default: boolean;
  static: boolean;
  description: string;
}
