/**
 * This file was automatically generated by jyst package.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run jyst to regenerate this file.
 */

/**
 * Arrays sharing the same items javaType collapse to reference the canonical one
 */
export interface SharedArrayItems {
  card: {
    name: 'orders_blocked_card' | 'chargebacks_received_card';
  }[];
  narrow: SharedArrayItems['card'];
}
