/**
 * This file was automatically generated by jyst package.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run jyst to regenerate this file.
 */

/**
 * Schema with a property named title (regression test for normalizeSchemaTitle)
 */
export interface TitleProperty {
  title: string;
  type: string;
}
